"""Writers for persisting DLS data structures back to XML."""
import logging
import xml.etree.ElementTree as ET
from typing import List, Optional
from xml.dom import minidom

from .models import DLSv1Data, DLSv2Data, SirenItem, SirenSettings

logger = logging.getLogger(__name__)


class DLSv1Writer:
    """Serialize DLS v1 data structures into XML."""

    @staticmethod
    def write(data: DLSv1Data, output_path: str, lost_features: Optional[List[str]] = None):
        logger.info("Writing DLS v1 file: %s", output_path)
        root = ET.Element("Model")
        root.append(ET.Comment(" DLS v1.4 VEHICLE CONFIGURATION FILE - Generated by DLS Tool "))

        lost_features = lost_features or []
        if lost_features:
            root.append(ET.Comment(" NOTE: Conversion from DLS v2 to DLS v1 may result in loss of certain features. "))
            comment_text = " The following features were lost during conversion: " + ", ".join(lost_features) + " "
            root.append(ET.Comment(comment_text))

        stage_settings = ET.SubElement(root, "StageSettings")
        ET.SubElement(stage_settings, "Stage1Enabled").text = str(data.stage1_enabled).lower()
        ET.SubElement(stage_settings, "Stage2Enabled").text = str(data.stage2_enabled).lower()
        ET.SubElement(stage_settings, "Stage3Enabled").text = str(data.stage3_enabled).lower()
        ET.SubElement(stage_settings, "CustomStage1Enabled").text = str(data.custom_stage1_enabled).lower()
        ET.SubElement(stage_settings, "CustomStage2Enabled").text = str(data.custom_stage2_enabled).lower()
        ET.SubElement(stage_settings, "GetStage3FromCarcols").text = str(data.get_stage3_from_carcols).lower()

        special_modes = ET.SubElement(root, "SpecialModes")
        ET.SubElement(special_modes, "SirenUI").text = data.siren_ui
        ET.SubElement(special_modes, "PresetSirenOnLeaveVehicle").text = data.preset_siren_on_leave

        wail_setup = ET.SubElement(special_modes, "WailSetup")
        ET.SubElement(wail_setup, "WailSetupEnabled").text = str(data.wail_setup_enabled).lower()
        ET.SubElement(wail_setup, "WailLightStage").text = data.wail_light_stage
        ET.SubElement(wail_setup, "WailSirenTone").text = data.wail_siren_tone

        steady_burn = ET.SubElement(special_modes, "SteadyBurn")
        ET.SubElement(steady_burn, "SteadyBurnEnabled").text = str(data.steady_burn_enabled).lower()
        ET.SubElement(steady_burn, "Pattern").text = data.steady_burn_pattern
        ET.SubElement(steady_burn, "Sirens").text = data.steady_burn_sirens

        sound_settings = ET.SubElement(root, "SoundSettings")
        ET.SubElement(sound_settings, "Tone1").text = data.tone1
        ET.SubElement(sound_settings, "Tone2").text = data.tone2
        ET.SubElement(sound_settings, "Tone3").text = data.tone3
        ET.SubElement(sound_settings, "Tone4").text = data.tone4
        ET.SubElement(sound_settings, "Horn").text = data.horn
        ET.SubElement(sound_settings, "AirHornInterruptsSiren").text = str(data.air_horn_interrupts_siren).lower()

        traffic_advisory = ET.SubElement(root, "TrafficAdvisory")
        ET.SubElement(traffic_advisory, "Type").text = data.traffic_advisory_type
        ET.SubElement(traffic_advisory, "DivergeOnly").text = str(data.traffic_advisory_diverge_only).lower()
        ET.SubElement(traffic_advisory, "AutoEnableStages").text = data.traffic_advisory_auto_enable_stages
        ET.SubElement(traffic_advisory, "DefaultEnabledDirection").text = data.traffic_advisory_default_direction
        ET.SubElement(traffic_advisory, "AutoDisableStages").text = data.traffic_advisory_auto_disable_stages
        for pos in ["L", "EL", "CL", "C", "CR", "ER", "R"]:
            ET.SubElement(traffic_advisory, pos).text = data.traffic_advisory_patterns.get(pos, "")

        sirens = ET.SubElement(root, "Sirens")
        if data.stage1:
            DLSv1Writer._write_siren_settings(sirens, "Stage1", data.stage1)
        if data.stage2:
            DLSv1Writer._write_siren_settings(sirens, "Stage2", data.stage2)
        if data.stage3:
            DLSv1Writer._write_siren_settings(sirens, "Stage3", data.stage3)
        if data.custom_stage1:
            DLSv1Writer._write_siren_settings(sirens, "CustomStage1", data.custom_stage1)
        if data.custom_stage2:
            DLSv1Writer._write_siren_settings(sirens, "CustomStage2", data.custom_stage2)

        xml_str = DLSv1Writer._prettify(root)
        with open(output_path, "w", encoding="utf-8") as handle:
            handle.write(xml_str)
        logger.info("DLS v1 file written successfully")

    @staticmethod
    def _write_siren_settings(parent: ET.Element, tag: str, settings: SirenSettings):
        stage = ET.SubElement(parent, tag)
        ET.SubElement(stage, "timeMultiplier").set("value", str(settings.timeMultiplier))
        ET.SubElement(stage, "lightFalloffMax").set("value", str(settings.lightFalloffMax))
        ET.SubElement(stage, "lightFalloffExponent").set("value", str(settings.lightFalloffExponent))
        ET.SubElement(stage, "lightInnerConeAngle").set("value", str(settings.lightInnerConeAngle))
        ET.SubElement(stage, "lightOuterConeAngle").set("value", str(settings.lightOuterConeAngle))
        ET.SubElement(stage, "lightOffset").set("value", str(settings.lightOffset))
        ET.SubElement(stage, "textureName").text = settings.textureName
        ET.SubElement(stage, "sequencerBpm").set("value", str(settings.sequencerBpm))

        lhl = ET.SubElement(stage, "leftHeadLight")
        ET.SubElement(lhl, "sequencer").set("value", str(settings.leftHeadLight))
        rhl = ET.SubElement(stage, "rightHeadLight")
        ET.SubElement(rhl, "sequencer").set("value", str(settings.rightHeadLight))
        ltl = ET.SubElement(stage, "leftTailLight")
        ET.SubElement(ltl, "sequencer").set("value", str(settings.leftTailLight))
        rtl = ET.SubElement(stage, "rightTailLight")
        ET.SubElement(rtl, "sequencer").set("value", str(settings.rightTailLight))

        ET.SubElement(stage, "leftHeadLightMultiples").set("value", str(settings.leftHeadLightMultiples))
        ET.SubElement(stage, "rightHeadLightMultiples").set("value", str(settings.rightHeadLightMultiples))
        ET.SubElement(stage, "leftTailLightMultiples").set("value", str(settings.leftTailLightMultiples))
        ET.SubElement(stage, "rightTailLightMultiples").set("value", str(settings.rightTailLightMultiples))
        ET.SubElement(stage, "useRealLights").set("value", str(settings.useRealLights).lower())

        sirens_elem = ET.SubElement(stage, "sirens")
        for index, siren in enumerate(settings.sirens):
            DLSv1Writer._write_siren_item(sirens_elem, siren, index + 1)

    @staticmethod
    def _write_siren_item(parent: ET.Element, siren: SirenItem, index: int):
        item = ET.SubElement(parent, "Item")
        item.append(ET.Comment(f" Siren {index} "))

        rotation = ET.SubElement(item, "rotation")
        ET.SubElement(rotation, "delta").set("value", str(siren.rotation.get("delta", 0)))
        ET.SubElement(rotation, "start").set("value", str(siren.rotation.get("start", 0)))
        ET.SubElement(rotation, "speed").set("value", str(siren.rotation.get("speed", 0)))
        ET.SubElement(rotation, "sequencer").set("value", str(siren.rotation.get("sequencer", 0)))
        ET.SubElement(rotation, "multiples").set("value", str(siren.rotation.get("multiples", 1)))
        ET.SubElement(rotation, "direction").set("value", str(siren.rotation.get("direction", False)).lower())
        ET.SubElement(rotation, "syncToBpm").set("value", str(siren.rotation.get("syncToBpm", True)).lower())

        flashiness = ET.SubElement(item, "flashiness")
        ET.SubElement(flashiness, "delta").set("value", str(siren.flashiness.get("delta", 0)))
        ET.SubElement(flashiness, "start").set("value", str(siren.flashiness.get("start", 0)))
        ET.SubElement(flashiness, "speed").set("value", str(siren.flashiness.get("speed", 0)))
        ET.SubElement(flashiness, "sequencer").set("value", str(siren.flashiness.get("sequencer", 0)))
        ET.SubElement(flashiness, "multiples").set("value", str(siren.flashiness.get("multiples", 1)))
        ET.SubElement(flashiness, "direction").set("value", str(siren.flashiness.get("direction", False)).lower())
        ET.SubElement(flashiness, "syncToBpm").set("value", str(siren.flashiness.get("syncToBpm", True)).lower())

        corona = ET.SubElement(item, "corona")
        ET.SubElement(corona, "intensity").set("value", str(siren.corona.get("intensity", 50)))
        ET.SubElement(corona, "size").set("value", str(siren.corona.get("size", 1)))
        ET.SubElement(corona, "pull").set("value", str(siren.corona.get("pull", 0)))
        ET.SubElement(corona, "faceCamera").set("value", str(siren.corona.get("faceCamera", False)).lower())

        ET.SubElement(item, "color").set("value", siren.color)
        ET.SubElement(item, "intensity").set("value", str(siren.intensity))
        ET.SubElement(item, "lightGroup").set("value", str(siren.lightGroup))
        ET.SubElement(item, "rotate").set("value", str(siren.rotate).lower())
        ET.SubElement(item, "scale").set("value", str(siren.scale).lower())
        ET.SubElement(item, "scaleFactor").set("value", str(siren.scaleFactor))
        ET.SubElement(item, "flash").set("value", str(siren.flash).lower())
        ET.SubElement(item, "light").set("value", str(siren.light).lower())
        ET.SubElement(item, "spotLight").set("value", str(siren.spotLight).lower())
        ET.SubElement(item, "castShadows").set("value", str(siren.castShadows).lower())

    @staticmethod
    def _prettify(elem: ET.Element) -> str:
        rough_string = ET.tostring(elem, encoding="unicode")
        reparsed = minidom.parseString(rough_string)
        return reparsed.toprettyxml(indent="\t")


class DLSv2Writer:
    """Serialize DLS v2 data structures into XML."""

    @staticmethod
    def write(data: DLSv2Data, output_path: str):
        logger.info("Writing DLS v2 file: %s", output_path)
        root = ET.Element("Model")
        root.set("vehicles", data.vehicles)
        root.append(ET.Comment(" DLS v2 VEHICLE CONFIGURATION FILE - Generated by DLS Tool "))

        audio = ET.SubElement(root, "Audio")
        audio_modes = ET.SubElement(audio, "AudioModes")
        for mode in data.audio_modes:
            mode_elem = ET.SubElement(audio_modes, "AudioMode")
            mode_elem.set("name", mode.name)
            if mode.yield_enabled:
                yield_elem = ET.SubElement(mode_elem, "Yield")
                yield_elem.set("enabled", "true")
            sound = ET.SubElement(mode_elem, "Sound")
            if mode.soundset:
                sound.set("soundset", mode.soundset)
            if mode.soundbank:
                sound.set("soundbank", mode.soundbank)
            sound.text = mode.sound_name

        modes = ET.SubElement(root, "Modes")
        for mode in data.light_modes:
            mode_elem = ET.SubElement(modes, "Mode")
            mode_elem.set("name", mode.name)
            yield_elem = ET.SubElement(mode_elem, "Yield")
            yield_elem.set("enabled", str(mode.yield_enabled).lower())

            if mode.extras:
                extras = ET.SubElement(mode_elem, "Extras")
                for extra in mode.extras:
                    extra_elem = ET.SubElement(extras, "Extra")
                    extra_elem.set("ID", str(extra["id"]))
                    extra_elem.set("Enabled", str(extra["enabled"]).lower())

            if mode.siren_settings:
                DLSv1Writer._write_siren_settings(mode_elem, "SirenSettings", mode.siren_settings)

        xml_str = DLSv1Writer._prettify(root)
        with open(output_path, "w", encoding="utf-8") as handle:
            handle.write(xml_str)
        logger.info("DLS v2 file written successfully")
